### ISSUE TITLE
Bot not sending scheduled quote/Twitch notifications

### ISSUE THREAD

**Issue by banribanri** [brainfrozeno00o/xandybot-nodejs#23]
Added bot to a new server - but it currently didn't send the scheduled quote or any Twitch notification in NSFW channels

Looking into the code, it seems that getting channel info for these tasks happen **only** upon starting the bot.

It might be better to have its logic inside the cron job.

**Comment by brainfrozeno00o** [comment]
It makes more sense to add the logic to the cron job for Twitch stuff. I'll be thinking about that for the scheduled quote sending, however. Nice catch, nonetheless.
